blank_issues_enabled: false
contact_links:
  - name: XPR Ledger Documentation
    url: https://xprl.org/
    about: All things about XPRL
  - name: General question for the community
    url: https://community/
    about: Please ask and answer questions here.
  - name: Security bug bounty program
    url: https://bug-bounty/
    about: Please report security-relevant bugs in our software here.
